version: '2'
services:
    deepstream-search-provider:
        #image: deepstreamio/deepstream.io-provider-search-rethinkdb
        build: "../deepstream.io-provider-search-rethinkdb/0.1.2"
        environment:
            - DEEPSTREAM_HOST=deepstream
            - DEEPSTREAM_PORT=6021
            - RETHINKDB_HOST=rethinkdb
        depends_on:
            - deepstream
    deepstream:
        image: deepstreamio/deepstream.io
        build: "."
        ports:
            - "6020:6020"
            - "6021:6021"
        volumes:
            - ./conf:/usr/local/deepstream/conf
            - ./var:/usr/local/deepstream/var
        depends_on:
            - redis
            - rethinkdb
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
    rethinkdb:
        image: rethinkdb
        ports:
            - "28015:28015"
            - "8080:8080"
        volumes:
            - ./rethinkdb-data:/data
