version: '2'
services:
    deepstream-search-provider:
        image: deepstreamio/deepstream.io-provider-search-rethinkdb
        environment:
            - DEEPSTREAM_HOST=deepstream
            - RETHINKDB_HOST=rethinkdb
        depends_on:
            - deepstream
    deepstream:
        build: "."
        ports:
            - "6020:6020"
            - "6021:6021"
        depends_on:
            - redis
            - rethinkdb
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
    rethinkdb:
        image: rethinkdb
        ports:
            - "28015:28015"
            - "8080:8080"